name: Build / Make Release / Publish to OSS

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout whole branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        OS: 'GIT HUB'
        release.customUsername: kochetkov-ma
        release.customPassword: ${{ secrets.GIT_HUB_TOKEN }}
      with:
        gradle-version: current
        arguments: '--stacktrace
        -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}"
        -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}"
        check coveralls build'