name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: actions/setup-java@v1
      name: Set up JDK
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - uses: eskatos/gradle-command-action@v1
      name: Build with Gradle
      env:
        release.customUsername: kochetkov-ma
        release.customPassword: ${{ secrets.GIT_HUB_TOKEN }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        ossrhPassword: ${{ secrets.ossrhPassword }}
      with:
        gradle-version: current
        arguments: --stacktrace clean check build
