name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Build with Gradle
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: --stacktrace clean check build
