name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: actions/setup-java@v1
      name: Set up JDK
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - uses: eskatos/gradle-command-action@v1
      name: Build with Gradle
      env:
        OS: 'GIT HUB'
        release.customUsername: kochetkov-ma
        release.customPassword: ${{ secrets.GIT_HUB_TOKEN }}
      with:
        gradle-version: current
        arguments: '--scan --stacktrace
        -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Prelease.customUsername=kochetkov-ma
        -Prelease.customPassword=${{ secrets.GIT_HUB_TOKEN }}
        -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}"
        -Psigning.password=${{ secrets.GPG_SIGNING_PASSWORD }}
        clean check build'
    - name: Upload to oss sonatype
    if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    uses: eskatos/gradle-command-action@v1
    with:
      gradle-version: current
      arguments: '-PossrhUsername=kochetkov-ma -PossrhPassword=${{ secrets.ossrhPassword }} uploadArchives'