name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: actions/setup-java@v1
      name: Set up JDK
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - uses: eskatos/gradle-command-action@v1
      name: Build with Gradle
      env:
        OS: 'GIT HUB'
        release.customUsername: kochetkov-ma
        release.customPassword: ${{ secrets.GIT_HUB_TOKEN }}
      with:
        gradle-version: current
        arguments: '--stacktrace
        -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}"
        -Psigning.password=${{ secrets.GPG_SIGNING_PASSWORD }}
        build'
    - name: Add release git tag
      # if: github.ref == 'refs/heads/master'
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: '--info --stacktrace -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Prelease.customUsername=kochetkov-ma
        -Prelease.customPassword=${{ secrets.GIT_HUB_TOKEN }}
        release'
    - name: Upload to oss sonatype
      if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: '--info --stacktrace -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}"
        -Psigning.password=${{ secrets.GPG_SIGNING_PASSWORD }}
        -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        uploadArchives'
    - name: Create release description
      # if: github.ref == 'refs/heads/master'
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}