name: Create release tag

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout whole branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force
    - name: Add release git tag
      if: github.ref == 'refs/heads/master'
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: '--info --stacktrace -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Prelease.customUsername=kochetkov-ma
        -Prelease.customPassword=${{ secrets.GIT_HUB_TOKEN }}
        -Prelease.disableChecks
        -Prelease.pushTagsOnly
        release'