name: Make Release / Publish to OSS

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deep checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Increment major version
      if: contains(github.head_ref, 'feature/')
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: '--info --stacktrace -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Prelease.customUsername=kochetkov-ma
        -Prelease.customPassword=${{ secrets.GIT_HUB_TOKEN }}
        -Prelease.disableChecks
        -Prelease.pushTagsOnly
        -Prelease.versionIncrementer=incrementMajor
        release'
    - name: Increment minor version
      if: !contains(github.head_ref, 'feature/')
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: '--info --stacktrace -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        -Prelease.customUsername=kochetkov-ma
        -Prelease.customPassword=${{ secrets.GIT_HUB_TOKEN }}
        -Prelease.disableChecks
        -Prelease.pushTagsOnly
        -Prelease.versionIncrementer=incrementMinor
        release'
    - name: Upload to OSS sonatype
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: '--info --stacktrace -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}"
        -Psigning.password=${{ secrets.GPG_SIGNING_PASSWORD }}
        -PossrhUsername=kochetkov-ma
        -PossrhPassword=${{ secrets.ossrhPassword }}
        uploadArchives'
    - name: Create GitHub release description
      if: github.ref == 'refs/heads/master'
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}